# Define default hyperparameters
SEQUENCE_LENGTH = 8
BATCH_SIZE = 32
IMAGE_HEIGHT = 480 // 2
IMAGE_WIDTH = 640 // 2

EPOCHS = 50
LEARNING_RATE = 1e-4
PATIENCE = 10
DEBUG = False
FILENAME = f'./prep/weights-{SEQUENCE_LENGTH}_{IMAGE_HEIGHT}_{IMAGE_WIDTH}.h5'
