# Define default hyperparameters
SEQUENCE_LENGTH = 16
BATCH_SIZE = 8
IMAGE_HEIGHT = 480 // 10
IMAGE_WIDTH = 640 // 10

EPOCHS = 20
LEARNING_RATE = 1e-4
PATIENCE = 5
DEBUG = False
FILENAME = f'./prep/weights-{SEQUENCE_LENGTH}_{IMAGE_HEIGHT}_{IMAGE_WIDTH}.h5'
